
export const MenuItems = [
    {
        title:'Home',
        url:'/',
        cName:'nav-links'
    },
    {
        title:'About',
        url:'about',
        cName:'nav-links'
    },
    {
        title:'Skills',
        url:'skills',
        cName:'nav-links'
    },
    {
        title:'Education',
        url:'education',
        cName:'nav-links'
    },
    {
        title:'Experiences',
        url:'experiences',
        cName:'nav-links'
    },
    {
        title:'Projects',
        url:'projects',
        cName:'nav-links'
    },
    {
        title:'Contact',
        url:'contact',
        cName:'nav-links'
    },
]
